import type { Page } from "puppeteer-core";
import { GIFEncoder, applyPalette, quantize } from "gifenc";
import jpeg from "jpeg-js";
import { launchBrowser, BrowserError } from "./browser";

export type ClipAction = "scroll" | "draw_canvas" | "none";
export interface CaptureClipOptions { url: string; action?: ClipAction; durationMs?: number; fps?: number; width?: number; height?: number; quality?: number; proxy?: string; }
export interface CapturedClip { url: string; finalUrl: string; action: ClipAction; durationMs: number; fps: number; width: number; height: number; mimeType: "image/jpeg"; frames: string[]; frameCount: number; bytes: number; note: string; }
export interface CapturedGif extends Omit<CapturedClip, "mimeType" | "frames" | "bytes"> { mimeType: "image/gif"; dataUri: string; bytes: number; frameCount: number; note: string; }
const MAX_DURATION_MS = 6_000; const MAX_FRAMES = 30;
const sleep = (ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms));
async function performAction(page: Page, action: ClipAction, elapsedMs: number, durationMs: number): Promise<void> {
  if (action === "scroll") await page.evaluate(({ elapsed, duration }) => { const max = Math.max(0, document.documentElement.scrollHeight - window.innerHeight); window.scrollTo({ top: max * Math.min(1, elapsed / duration), behavior: "auto" }); }, { elapsed: elapsedMs, duration: durationMs });
  else if (action === "draw_canvas") await page.evaluate(({ elapsed, duration }) => { const canvas = document.querySelector("canvas") as HTMLCanvasElement | null; if (!canvas) return; const rect = canvas.getBoundingClientRect(); canvas.dispatchEvent(new PointerEvent("pointermove", { bubbles: true, clientX: rect.left + rect.width * Math.min(1, elapsed / duration), clientY: rect.top + rect.height * (0.5 + 0.2 * Math.sin(elapsed / 180)), pointerId: 1, buttons: 1 })); }, { elapsed: elapsedMs, duration: durationMs });
}
function options(opts: CaptureClipOptions) { const durationMs = Math.min(Math.max(Math.round(opts.durationMs ?? 4_000), 250), MAX_DURATION_MS); const fps = Math.min(Math.max(Math.round(opts.fps ?? 3), 1), 5); return { durationMs, fps, width: Math.min(Math.max(Math.round(opts.width ?? 960), 320), 1600), height: Math.min(Math.max(Math.round(opts.height ?? 540), 240), 1200), action: opts.action ?? "scroll" as ClipAction }; }
export async function captureActionFrames(opts: CaptureClipOptions): Promise<CapturedClip> { const { durationMs, fps, width, height, action } = options(opts); const parsed = new URL(opts.url); if (!/^https?:$/.test(parsed.protocol)) throw new BrowserError("URL must use http or https", "E_URL_SCHEME"); const browser = await launchBrowser({ proxy: opts.proxy }); const frames: string[] = []; const started = Date.now(); try { const page = await browser.newPage(); await page.setViewport({ width, height, deviceScaleFactor: 1 }); await page.goto(parsed.toString(), { waitUntil: "domcontentloaded", timeout: 30_000 }); const until = Date.now() + durationMs; while (Date.now() < until && frames.length < MAX_FRAMES) { await performAction(page, action, Math.min(durationMs, Date.now() - started), durationMs); const image = await page.screenshot({ type: "jpeg", quality: Math.min(Math.max(opts.quality ?? 65, 30), 85), encoding: "binary" }); frames.push(Buffer.from(image).toString("base64")); await sleep(Math.min(Math.max(200, Math.round(1000 / fps)), Math.max(0, until - Date.now()))); } return { url: opts.url, finalUrl: page.url(), action, durationMs, fps, width, height, mimeType: "image/jpeg", frames, frameCount: frames.length, bytes: frames.reduce((n, f) => n + Buffer.byteLength(f, "base64"), 0), note: "Ordered JPEG base64 frames." }; } catch (err) { throw err instanceof BrowserError ? err : new BrowserError(`Clip capture failed: ${err instanceof Error ? err.message : String(err)}`, "E_CLIP"); } finally { await browser.close().catch(() => undefined); } }
export async function captureActionGif(opts: CaptureClipOptions): Promise<CapturedGif> { const { durationMs, fps, width, height, action } = options(opts); const parsed = new URL(opts.url); if (!/^https?:$/.test(parsed.protocol)) throw new BrowserError("URL must use http or https", "E_URL_SCHEME"); const browser = await launchBrowser({ proxy: opts.proxy }); const rgbaFrames: Uint8Array[] = []; let finalUrl = parsed.toString(); try { const page = await browser.newPage(); await page.setViewport({ width, height, deviceScaleFactor: 1 }); await page.goto(parsed.toString(), { waitUntil: "domcontentloaded", timeout: 30_000 }); const until = Date.now() + durationMs; while (Date.now() < until && rgbaFrames.length < MAX_FRAMES) { await performAction(page, action, Math.min(durationMs, Date.now()), durationMs); const jpegBytes = await page.screenshot({ type: "jpeg", quality: Math.min(Math.max(opts.quality ?? 65, 30), 85), encoding: "binary" }); rgbaFrames.push(jpeg.decode(Buffer.from(jpegBytes), { useTArray: true }).data); await sleep(Math.min(Math.max(200, Math.round(1000 / fps)), Math.max(0, until - Date.now()))); } finalUrl = page.url(); const gif = GIFEncoder(); for (const rgba of rgbaFrames) { const palette = quantize(rgba, 256); gif.writeFrame(applyPalette(rgba, palette), width, height, { palette, delay: Math.round(1000 / fps), repeat: 0 }); } gif.finish(); const data = Buffer.from(gif.bytes()); return { url: opts.url, finalUrl, action, durationMs, fps, width, height, mimeType: "image/gif", dataUri: `data:image/gif;base64,${data.toString("base64")}`, bytes: data.length, frameCount: rgbaFrames.length, note: "Animated GIF encoded with pure-JS gifenc; JPEG decoding uses pure-JS jpeg-js." }; } catch (err) { throw err instanceof BrowserError ? err : new BrowserError(`GIF capture failed: ${err instanceof Error ? err.message : String(err)}`, "E_GIF"); } finally { await browser.close().catch(() => undefined); } }
